### ISSUE TITLE
Add new form inputs to Members/SongBook Page

### ISSUE THREAD

**Issue by bryson-palmer** [Bryson-Palmer/song-bird#2]
Build HTML

**Comment by Tskading** [comment]
I am working on converting all of our html into handlebars.  Not there yet, I'll reach out with questions, thanks all.

**Comment by Tskading** [comment]
All pages converted to hbrs.  Page layouts and partials for header and modal, with dynamic html being produced with JQuery (members page) and handlebars (song page).
