### ISSUE TITLE
handlebars issues

### ISSUE THREAD

**Issue by bryson-palmer** [Bryson-Palmer/song-bird#5]
Following handlebars layout  like it is described in the projects tab.
Let's reserve index.handlebars for our first page upon passing user authentication. It would be default get request to display all artists.

In the create song.handlebars, following previous HW examples, input and label should be lined up with one another. Also, if you could make the `for` in the label and the `id` in input/textarea words match while giving the unique word to the `name`. Also, please make the `input` for lyrics a `textarea`. Might have to add `rows = a number` and `cols = a number`.

Here is an example that I was following. 
They wrap each field in a div. Not sure what the benefit is but might be useful. Lastly, their submit button looks different. Right now we have `input` instead of button with >Add Song< as it's text. 

We could just use from the `<h1>` down to the end of `form` as a partial and plug it into the index. It will keep a uniform layout for the logo, nav bar/links, and what other generic stuff we have around our pages. 

On a side note, we should put the songbird/songbirdie in the head title. Let me know what you think.

```<h2>Add a Quote</h2>

<form class="create-form">

  <div class="form-group">
    <label for="auth">Author:</label>
    <input type="text" id="auth" name="author">
  </div>

  <div class="form-group">
    <label for="quo">Quote:</label>
    <textarea id="quo" name="quote" rows="8" cols="40"></textarea>
  </div>

  <button type="submit">Add Quote</button>
</form>```

**Comment by Tskading** [comment]
Got one /createSong page up and to main.
